name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python - --version 1.2.1
          $HOME/.local/bin/poetry install

      - name: Run tests
        run: |
          $HOME/.local/bin/poetry run pytest

      - name: Build wheels
        run: |
          $HOME/.local/bin/poetry version $(git tag --points-at HEAD)
          $HOME/.local/bin/poetry build

      - name: Upload
        env:
          USERNAME: __token__
          PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          $HOME/.local/bin/poetry publish --username=$USERNAME --password=$PASSWORD
